-- CreateTable
CREATE TABLE "category" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "createat" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateat" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
